apiVersion: v2
name: mern-app
description: A Helm chart for the MERN application
version: 1.0.0
dependencies:
  - name: client
    version: 1.0.0
    repository: file://charts/client
  - name: server
    version: 1.0.0
    repository: file://charts/server
  - name: mongodb
    version: 1.0.0
    repository: file://charts/mongodb
