replicaCount: 1
image:
  repository: chrayef/mern-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

env:
  - name: MONGO_URI
    value: mongodb://mongo:27017/mern-app
  - name: PORT_SERVER
    value: "9000"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host:
      paths:
        - path: /api/(.*)
          pathType: ImplementationSpecific
  tls: []


